#!/bin/bash

#PBS -l nodes=1:ppn=10,walltime=2:00:00,feature=rhel7
#PBS -j oe
#PBS -m abe
#PBS -M mdb5946@psu.edu
#PBS -A wff3_a_g_hc_default

# Go to the correct place

cd $PBS_O_WORKDIR

module load python/3.6.8
module load anaconda3
source activate /storage/home/mdb5946/.conda/envs/qiime2-2020.8

#filter out contaminant ASVs from decontam
qiime feature-table filter-features \
  --i-table feature_table_no_MtCpUnEuk.qza \
  --p-exclude-ids \
  --m-metadata-file asv_to_remove.txt \
  --o-filtered-table feature_table_no_contam.qza

#summarize new feature tabulate
qiime feature-table summarize \
  --i-table feature_table_no_contam.qza \
  --o-visualization feature_table_no_contam.qzv

#filter seqs to remove mt,cp,un,euk,contam for phylogeny
qiime feature-table filter-seqs \
  --i-data ../rep-seqs.qza \
  --i-table feature_table_no_contam.qza \
  --o-filtered-data rep-seqs_no_contam.qza

#visualize, should have  sequences (subtract cp,mt,un,euk,contam) - !
qiime feature-table tabulate-seqs \
  --i-data rep-seqs_no_contam.qza \
  --o-visualization rep-seqs_no_contam.qzv

#generate a tree for phylogenetic diversity analyses
qiime phylogeny align-to-tree-mafft-fasttree \
  --i-sequences rep-seqs_no_contam.qza \
  --o-alignment aligned-rep-seqs_no_contam.qza \
  --o-masked-alignment masked-aligned-rep-seqs_no_contam.qza \
  --o-tree unrooted-tree_silva.qza \
  --o-rooted-tree rooted-tree_silva.qza

#produce alpha-rarefaction curve
qiime diversity alpha-rarefaction \
  --i-table feature_table_no_contam.qza \
  --i-phylogeny rooted-tree_silva.qza \
  --p-max-depth 21000 \
  --m-metadata-file ../metadata2_16s_ny.tsv \
  --o-visualization alpha-rarefaction_silva.qzv

#export feature table to otu table (puts it in a folder called out-table.biom)
qiime tools export \
  --input-path feature_table_no_contam.qza \
  --output-path otu_table_silva.biom

#convert to tsv file for phyloseq
biom convert -i  ./otu_table_silva.biom/feature-table.biom -o ./otu_table_silva.biom/feature-table.tsv --to-tsv

#export tree for phyloseq
qiime tools export \
  --input-path rooted-tree_silva.qza \
  --output-path exported-tree_silva
